---
# tasks file for ansible-raid-check
- name: Set config option
  lineinfile:
    path: /etc/sysconfig/raid-check
    regexp: '^{{ item.0 }}=.*'
    line: "{{ item.0 }}={{ item.1|string|quote }}"
  with_together:
    - [
      "ENABLED",
      "CHECK",
      "NICE",
      "CHECK_DEVS",
      "REPAIR_DEVS",
      "SKIP_DEVS",
      "MAXCONCURRENT"
    ]
    - [
      "{{ raid_check_enabled }}",
      "{{ raid_check_check }}",
      "{{ raid_check_nice }}",
      "{{ raid_check_check_devs }}",
      "{{ raid_check_repair_devs }}",
      "{{ raid_check_skip_devs }}",
      "{{ raid_check_maxconcurrent }}"
    ]

- name: Set time for cronjob execution
  template:
    src: "raid-check.j2"
    dest: "/etc/cron.d/raid-check"
